# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install --dev
          - pipenv run invoke tests
